### ISSUE TITLE
roadmap question: git commit signing / compatibility with smimesign

### ISSUE THREAD

**Issue by dagheyman** [FiloSottile/yubikey-agent#24]
Would it make sense to have this project compatible with [smimesign](https://github.com/github/smimesign) from GitHub? Or to implement similar functionality for git commit signing.

**Comment by FiloSottile** [comment]
I don't actually believe git commit signing is any use. (Some discussion [here](https://twitter.com/FiloSottile/status/1248110291751231488).)

My recommendation instead is to use OpenSSH's new file signing support to sign releases.

Anyway, smimesign is pretty orthogonal to yubikey-agent, which is an SSH agent. You might have to send a SIGHUP to yubikey-agent before using smimesign, so it will release the lock on the YubiKey, but otherwise things should work.

**Comment by biosan** [comment]
@FiloSottile could you provide more information about signing files with OpenSSH? I've not found any way to do it using a `ssh-agent`.

I really want to ditch GPG completely and signing files is the only missing piece (when `age` will support SSH Agent)

**Comment by jstasiak** [comment]
@FiloSottile Where do I find out more about this "OpenSSH's new file signing support"? I'm excited, because having some nice non-gpg signing solution with Yubikey integration is something I've been looking for for a while, but I can't find anything when searching for "openssh file signing" or just "openssh signing".

**Comment by biosan** [comment]
@jstasiak It's hidden inside `ssh-keygen` (definitely not good UX)

From [`ssh-keygen` manpage](https://man.openbsd.org/ssh-keygen#Y~3):
> **-Y sign**
> Cryptographically sign a file or some data using a SSH key. When signing, ssh-keygen accepts zero or more files to sign on the command-line - if no files are specified then ssh-keygen will sign data presented on standard input. Signatures are written to the path of the input file with “.sig” appended, or to standard output if the message to be signed was read from standard input.
>
> The key used for signing is specified using the -f option and may refer to either a private key, or a public key with the private half available via ssh-agent(1). An additional signature namespace, used to prevent signature confusion across different domains of use (e.g. file signing vs email signing) must be provided via the -n flag. Namespaces are arbitrary strings, and may include: “file” for file signing, “email” for email signing. For custom uses, it is recommended to use names following a NAMESPACE@YOUR.DOMAIN pattern to generate unambiguous namespaces.
