### ISSUE TITLE
Feature request: User configurable delay before "Waiting for YubiKey touch..." notification

### ISSUE THREAD

**Issue by theblazehen** [FiloSottile/yubikey-agent#68]
I don't have my yubikey in direct eye view, would be convenient if the desktop notification showed immediately or on a configurable delay

**Comment by jcharaoui** [comment]
I have the same problem. I sometimes end up generating a Yubico OTP code because I'm too quick to touch the Yubikey, or something on the console seems to hang (eg. a script), but it's actually waiting for the token to be touched. A visual notification would sensibly improve the UX with yubikey-agent.

**Comment by jcharaoui** [comment]
So looking through the commit history I realized that a visual notification is indeed implemented, but I wasn't seeing it because my system (Debian 11) was missing the `libnotify-bin` package. I still support the idea of adding an option to avoid the 5 second delay.

**Comment by FiloSottile** [comment]
I see the use case, but yubikey-agent is meant to have no configuration options and the current behavior avoids visual noise for most users.
