### ISSUE TITLE
Does this project still supported/maintained?

### ISSUE THREAD

**Issue by asychev** [FiloSottile/yubikey-agent#76]
Hi!

Thanks for all the efforts you put into this project!
But does this project still supported/maintained?

Are there any future plans or roadmap?

I see Issues just not get any attention and PRs are ignored/closed.

**Comment by FiloSottile** [comment]
Hello! I think this project does what it should pretty well, and I am a bit fan of "finishing" projects.

I read all issues, and there aren't any major ones open. If something happened that were to break the tool I would fix it.

About future plans, there are a couple things I would like to get around to, but not timeline

* multi-key and multi-token support
* an advanced command to add a new key in one of the retired slots, which can have custom policies, be imported, etc. (although maybe this will come in the form of docs on how to do that with existing tools, so that the key will be supported by yubikey-agent)
* eventually, age support
