### ISSUE TITLE
 yubikey-agent -setup does not work

### ISSUE THREAD

**Issue by asychev** [FiloSottile/yubikey-agent#78]
With the fresh YubiKey 5C NFC on OSX 11.2.1:

```
$ ykman info
Device type: YubiKey 5C NFC
Serial number: REDACTED
Firmware version: 5.2.7
Form factor: Keychain (USB-C)
Enabled USB interfaces: OTP+FIDO+CCID
NFC interface is enabled.

Applications	USB    	NFC
OTP     	Enabled	Disabled
FIDO U2F	Enabled	Enabled
OpenPGP 	Enabled	Enabled
PIV     	Enabled	Enabled
OATH    	Enabled	Enabled
FIDO2   	Enabled	Enabled
```

```
$ yubikey-agent -setup
🔐 The PIN is up to 8 numbers, letters, or symbols. Not just numbers!
❌ The key will be lost if the PIN and PUK are locked after 3 incorrect tries.

Choose a new PIN/PUK:
Repeat PIN/PUK:

🧪 Reticulating splines...
‼️  The default Management Key did not work

If you know what you're doing, reset PIN, PUK, and
Management Key to the defaults before retrying.

If you want to wipe all PIV keys and start fresh,
use --really-delete-all-piv-keys ⚠️
```
What could be a problem?

**Comment by asychev** [comment]
@FiloSottile Any chance you could help?

**Comment by asychev** [comment]
OK, seems like this project is not maintained anymore despite the statement made on https://github.com/FiloSottile/yubikey-agent/issues/76

**Comment by gador** [comment]
@asychev if you're still looking for an answer (and anyone else):

I had the same error. It turns out that the new yubikeys want a pin of at least 6 characters. Entering a PIN less than that will result in the error message `The default Management Key did not work`. 

I worked around the issue by reseting the device with 
`yubikey-agent --really-delete-all-piv-keys -setup` and then entering a new PIN with at least 6 characters. 

Also, the error message the first time (when entering a PIN which is too short) is `The default PIN did not work`. After that first try it will change to  `The default Management Key did not work`.
