### ISSUE TITLE
Attempting to use yubikey fails: "could not get public key"

### ISSUE THREAD

**Issue by cinerea0** [FiloSottile/yubikey-agent#80]
I know that yubikeys not set up with this tool aren't officially supported, but I thought this was odd. Here's the guide I used to set up my yubikey: https://github.com/drduh/YubiKey-Guide#creating-keys.

Output from yubikey-agent when attempting to use the yubikey:
```
2021/02/17 22:45:03 Connecting to the YubiKey...
2021/02/17 22:45:03 agent 11: could not get public key: command failed: smart card error 6a82: data object or application not found
```

Output of `ykman info`:
```
Device type: YubiKey 5 NFC
Serial number: 11417625
Firmware version: 5.2.4
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP+FIDO+CCID
NFC interface is enabled.

Applications	USB    	NFC
OTP     	Enabled	Enabled	
FIDO U2F	Enabled	Enabled	
OpenPGP 	Enabled	Enabled	
PIV     	Enabled	Enabled	
OATH    	Enabled	Enabled	
FIDO2   	Enabled	Enabled
```

**Comment by FiloSottile** [comment]
That guide uses the OpenPGP applet (except for bizzarrely making you change the PIV PUK, which I think is just a mistake in that guide), yubikey-agent uses the PIV applet. They don't share keys.

**Comment by KerickHowlett** [comment]
I hope if it's okay for me to continue this conversation since I (with the help of the friend) also went through the DrDuh process mentioned in the OP to setup my Yubikey for GPG, which naturally includes using PUK.

However, I'm still also largely unfamiliar with the world of encryptions outside of the most fundamental basics. (While I did graduate from college in InfoSec, I ended up becoming a software engineer, so I'm rather rusty in all of this. lol)

Would it be okay for me to ask what are the trade-offs between what the DrDuh instructions offer versus `yubikey-agent`? Is one more secure than the other?

`yubikey-agent` is _infinitely_ simpler to setup! The DrDuh method is not only time consuming just to read -- even though it is quite informative -- took an air-gapped Raspberry Pi and an encrypted thumbdrive, as well as a few hours to figure out what I was doing and to actually get it done! `yubikey-agent` took me just under a minute to set up on my spare Yubikey.

For my purposes, I'm using my Yubikey for authentication (websites & apps), git commit signing, some encryption/decryption, MFA, accessing my desktop (as soon as I set that up), remote SSH access, and maybe a static password generator. Is `yubikey-agent` not suitable for any of the things I just mentioned?
