### ISSUE TITLE
wish: document when the SSH key expires

### ISSUE THREAD

**Issue by markstos** [FiloSottile/yubikey-agent#85]
From reading the source code, it appears the key generated during setup expires in 42 years or essentially never:

https://github.com/FiloSottile/yubikey-agent/blob/main/setup.go#L163

I have no objection to that policy, but I think it's worth a mention in the README, as other Yubikey/SSH solution have defaulted to much shorter expiration lengths.

**Comment by FiloSottile** [comment]
SSH keys don't have expiration dates, that timestamp is only there because it's a required field of the X.509 certificate that is just used as a way to get PIV to store the public key. Even if it were in the past, everything would keep working, and no one outside the YubiKey would know.

What other solutions have expiration?

**Comment by markstos** [comment]
I must be thinking of a GPG-based solution I tried. Thanks for the quick reply!
