### ISSUE TITLE
Keychain caching on macOS should be opt-in

### ISSUE THREAD

**Issue by FiloSottile** [FiloSottile/yubikey-agent#93]
#46 introduced opt-in external caching of the PIN by passing `allow-external-password-cache` to pinenetry. pinenetry-mac regrettably checks that box by default. We should find a way to disable that.

We should also document that this is supported, as it makes for a nice flow where a very complex PIN is used to tie a YubiKey Nano to the machine it's plugged in.

**Comment by jacobvosmaer** [comment]
I accidentally upgraded my `yubikey-agent` installation and spent quite some time trying to understand why it no longer uses the macOS Keychain. It appears that the reason is  c9e9f88ea9ed076fc44fc9baa00054d4592fa704, which closed this issue. I am now confused by the messaging.

1. This issue says Keychain use should be possible as an opt-in
2. c9e9f88ea9ed076fc44fc9baa00054d4592fa704 locks Darwin into using AppleScript without any apparent Keychain support, and the commit message suggests using the Keychain is bad
3. c9e9f88ea9ed076fc44fc9baa00054d4592fa704 simultaneously adds opt-in Keychain support for `!darwin` builds

So is using a keychain good or bad?

@FiloSottile As a user, I'd like to have Keychain support back, and I could see if I can rig something up where yubikey-agent shells out to the macos `security` command. Would you be open to that?
